// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

var TableNames = struct {
	AuthTokens  string
	Friendships string
	Messages    string
	RemoteUsers string
	Users       string
}{
	AuthTokens:  "auth_tokens",
	Friendships: "friendships",
	Messages:    "messages",
	RemoteUsers: "remote_users",
	Users:       "users",
}
