// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// Friendship is an object representing the database table.
type Friendship struct {
	ID       int      `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID   null.Int `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	FriendID null.Int `boil:"friend_id" json:"friend_id,omitempty" toml:"friend_id" yaml:"friend_id,omitempty"`

	R *friendshipR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L friendshipL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FriendshipColumns = struct {
	ID       string
	UserID   string
	FriendID string
}{
	ID:       "id",
	UserID:   "user_id",
	FriendID: "friend_id",
}

// friendshipR is where relationships are stored.
type friendshipR struct {
	User   *User
	Friend *User
}

// friendshipL is where Load methods for each relationship are stored.
type friendshipL struct{}

var (
	friendshipColumns               = []string{"id", "user_id", "friend_id"}
	friendshipColumnsWithoutDefault = []string{"user_id", "friend_id"}
	friendshipColumnsWithDefault    = []string{"id"}
	friendshipPrimaryKeyColumns     = []string{"id"}
)

type (
	// FriendshipSlice is an alias for a slice of pointers to Friendship.
	// This should generally be used opposed to []Friendship.
	FriendshipSlice []*Friendship
	// FriendshipHook is the signature for custom Friendship hook methods
	FriendshipHook func(boil.Executor, *Friendship) error

	friendshipQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	friendshipType                 = reflect.TypeOf(&Friendship{})
	friendshipMapping              = queries.MakeStructMapping(friendshipType)
	friendshipPrimaryKeyMapping, _ = queries.BindMapping(friendshipType, friendshipMapping, friendshipPrimaryKeyColumns)
	friendshipInsertCacheMut       sync.RWMutex
	friendshipInsertCache          = make(map[string]insertCache)
	friendshipUpdateCacheMut       sync.RWMutex
	friendshipUpdateCache          = make(map[string]updateCache)
	friendshipUpsertCacheMut       sync.RWMutex
	friendshipUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var friendshipBeforeInsertHooks []FriendshipHook
var friendshipBeforeUpdateHooks []FriendshipHook
var friendshipBeforeDeleteHooks []FriendshipHook
var friendshipBeforeUpsertHooks []FriendshipHook

var friendshipAfterInsertHooks []FriendshipHook
var friendshipAfterSelectHooks []FriendshipHook
var friendshipAfterUpdateHooks []FriendshipHook
var friendshipAfterDeleteHooks []FriendshipHook
var friendshipAfterUpsertHooks []FriendshipHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Friendship) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range friendshipBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Friendship) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range friendshipBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Friendship) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range friendshipBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Friendship) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range friendshipBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Friendship) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range friendshipAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Friendship) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range friendshipAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Friendship) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range friendshipAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Friendship) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range friendshipAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Friendship) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range friendshipAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFriendshipHook registers your hook function for all future operations.
func AddFriendshipHook(hookPoint boil.HookPoint, friendshipHook FriendshipHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		friendshipBeforeInsertHooks = append(friendshipBeforeInsertHooks, friendshipHook)
	case boil.BeforeUpdateHook:
		friendshipBeforeUpdateHooks = append(friendshipBeforeUpdateHooks, friendshipHook)
	case boil.BeforeDeleteHook:
		friendshipBeforeDeleteHooks = append(friendshipBeforeDeleteHooks, friendshipHook)
	case boil.BeforeUpsertHook:
		friendshipBeforeUpsertHooks = append(friendshipBeforeUpsertHooks, friendshipHook)
	case boil.AfterInsertHook:
		friendshipAfterInsertHooks = append(friendshipAfterInsertHooks, friendshipHook)
	case boil.AfterSelectHook:
		friendshipAfterSelectHooks = append(friendshipAfterSelectHooks, friendshipHook)
	case boil.AfterUpdateHook:
		friendshipAfterUpdateHooks = append(friendshipAfterUpdateHooks, friendshipHook)
	case boil.AfterDeleteHook:
		friendshipAfterDeleteHooks = append(friendshipAfterDeleteHooks, friendshipHook)
	case boil.AfterUpsertHook:
		friendshipAfterUpsertHooks = append(friendshipAfterUpsertHooks, friendshipHook)
	}
}

// OneP returns a single friendship record from the query, and panics on error.
func (q friendshipQuery) OneP() *Friendship {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single friendship record from the query.
func (q friendshipQuery) One() (*Friendship, error) {
	o := &Friendship{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for friendships")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Friendship records from the query, and panics on error.
func (q friendshipQuery) AllP() FriendshipSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Friendship records from the query.
func (q friendshipQuery) All() (FriendshipSlice, error) {
	var o []*Friendship

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Friendship slice")
	}

	if len(friendshipAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Friendship records in the query, and panics on error.
func (q friendshipQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Friendship records in the query.
func (q friendshipQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count friendships rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q friendshipQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q friendshipQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if friendships exists")
	}

	return count > 0, nil
}

// UserG pointed to by the foreign key.
func (o *Friendship) UserG(mods ...qm.QueryMod) userQuery {
	return o.User(boil.GetDB(), mods...)
}

// User pointed to by the foreign key.
func (o *Friendship) User(exec boil.Executor, mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(exec, queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// FriendG pointed to by the foreign key.
func (o *Friendship) FriendG(mods ...qm.QueryMod) userQuery {
	return o.Friend(boil.GetDB(), mods...)
}

// Friend pointed to by the foreign key.
func (o *Friendship) Friend(exec boil.Executor, mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.FriendID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(exec, queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
} // LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (friendshipL) LoadUser(e boil.Executor, singular bool, maybeFriendship interface{}) error {
	var slice []*Friendship
	var object *Friendship

	count := 1
	if singular {
		object = maybeFriendship.(*Friendship)
	} else {
		slice = *maybeFriendship.(*[]*Friendship)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &friendshipR{}
		}
		args[0] = object.UserID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &friendshipR{}
			}
			args[i] = obj.UserID
		}
	}

	query := fmt.Sprintf(
		"select * from \"users\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}
	defer results.Close()

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if len(friendshipAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.User = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID.Int == foreign.ID {
				local.R.User = foreign
				break
			}
		}
	}

	return nil
}

// LoadFriend allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (friendshipL) LoadFriend(e boil.Executor, singular bool, maybeFriendship interface{}) error {
	var slice []*Friendship
	var object *Friendship

	count := 1
	if singular {
		object = maybeFriendship.(*Friendship)
	} else {
		slice = *maybeFriendship.(*[]*Friendship)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &friendshipR{}
		}
		args[0] = object.FriendID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &friendshipR{}
			}
			args[i] = obj.FriendID
		}
	}

	query := fmt.Sprintf(
		"select * from \"users\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}
	defer results.Close()

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if len(friendshipAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Friend = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FriendID.Int == foreign.ID {
				local.R.Friend = foreign
				break
			}
		}
	}

	return nil
}

// SetUserG of the friendship to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Friendships.
// Uses the global database handle.
func (o *Friendship) SetUserG(insert bool, related *User) error {
	return o.SetUser(boil.GetDB(), insert, related)
}

// SetUserP of the friendship to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Friendships.
// Panics on error.
func (o *Friendship) SetUserP(exec boil.Executor, insert bool, related *User) {
	if err := o.SetUser(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUserGP of the friendship to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Friendships.
// Uses the global database handle and panics on error.
func (o *Friendship) SetUserGP(insert bool, related *User) {
	if err := o.SetUser(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUser of the friendship to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Friendships.
func (o *Friendship) SetUser(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"friendships\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, friendshipPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID.Int = related.ID
	o.UserID.Valid = true

	if o.R == nil {
		o.R = &friendshipR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Friendships: FriendshipSlice{o},
		}
	} else {
		related.R.Friendships = append(related.R.Friendships, o)
	}

	return nil
}

// RemoveUserG relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *Friendship) RemoveUserG(related *User) error {
	return o.RemoveUser(boil.GetDB(), related)
}

// RemoveUserP relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Panics on error.
func (o *Friendship) RemoveUserP(exec boil.Executor, related *User) {
	if err := o.RemoveUser(exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveUserGP relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle and panics on error.
func (o *Friendship) RemoveUserGP(related *User) {
	if err := o.RemoveUser(boil.GetDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Friendship) RemoveUser(exec boil.Executor, related *User) error {
	var err error

	o.UserID.Valid = false
	if err = o.Update(exec, "user_id"); err != nil {
		o.UserID.Valid = true
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.User = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Friendships {
		if o.UserID.Int != ri.UserID.Int {
			continue
		}

		ln := len(related.R.Friendships)
		if ln > 1 && i < ln-1 {
			related.R.Friendships[i] = related.R.Friendships[ln-1]
		}
		related.R.Friendships = related.R.Friendships[:ln-1]
		break
	}
	return nil
}

// SetFriendG of the friendship to the related item.
// Sets o.R.Friend to related.
// Adds o to related.R.FriendFriendships.
// Uses the global database handle.
func (o *Friendship) SetFriendG(insert bool, related *User) error {
	return o.SetFriend(boil.GetDB(), insert, related)
}

// SetFriendP of the friendship to the related item.
// Sets o.R.Friend to related.
// Adds o to related.R.FriendFriendships.
// Panics on error.
func (o *Friendship) SetFriendP(exec boil.Executor, insert bool, related *User) {
	if err := o.SetFriend(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetFriendGP of the friendship to the related item.
// Sets o.R.Friend to related.
// Adds o to related.R.FriendFriendships.
// Uses the global database handle and panics on error.
func (o *Friendship) SetFriendGP(insert bool, related *User) {
	if err := o.SetFriend(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetFriend of the friendship to the related item.
// Sets o.R.Friend to related.
// Adds o to related.R.FriendFriendships.
func (o *Friendship) SetFriend(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"friendships\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"friend_id"}),
		strmangle.WhereClause("\"", "\"", 2, friendshipPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FriendID.Int = related.ID
	o.FriendID.Valid = true

	if o.R == nil {
		o.R = &friendshipR{
			Friend: related,
		}
	} else {
		o.R.Friend = related
	}

	if related.R == nil {
		related.R = &userR{
			FriendFriendships: FriendshipSlice{o},
		}
	} else {
		related.R.FriendFriendships = append(related.R.FriendFriendships, o)
	}

	return nil
}

// RemoveFriendG relationship.
// Sets o.R.Friend to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *Friendship) RemoveFriendG(related *User) error {
	return o.RemoveFriend(boil.GetDB(), related)
}

// RemoveFriendP relationship.
// Sets o.R.Friend to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Panics on error.
func (o *Friendship) RemoveFriendP(exec boil.Executor, related *User) {
	if err := o.RemoveFriend(exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveFriendGP relationship.
// Sets o.R.Friend to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle and panics on error.
func (o *Friendship) RemoveFriendGP(related *User) {
	if err := o.RemoveFriend(boil.GetDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveFriend relationship.
// Sets o.R.Friend to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Friendship) RemoveFriend(exec boil.Executor, related *User) error {
	var err error

	o.FriendID.Valid = false
	if err = o.Update(exec, "friend_id"); err != nil {
		o.FriendID.Valid = true
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Friend = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.FriendFriendships {
		if o.FriendID.Int != ri.FriendID.Int {
			continue
		}

		ln := len(related.R.FriendFriendships)
		if ln > 1 && i < ln-1 {
			related.R.FriendFriendships[i] = related.R.FriendFriendships[ln-1]
		}
		related.R.FriendFriendships = related.R.FriendFriendships[:ln-1]
		break
	}
	return nil
}

// FriendshipsG retrieves all records.
func FriendshipsG(mods ...qm.QueryMod) friendshipQuery {
	return Friendships(boil.GetDB(), mods...)
}

// Friendships retrieves all the records using an executor.
func Friendships(exec boil.Executor, mods ...qm.QueryMod) friendshipQuery {
	mods = append(mods, qm.From("\"friendships\""))
	return friendshipQuery{NewQuery(exec, mods...)}
}

// FindFriendshipG retrieves a single record by ID.
func FindFriendshipG(id int, selectCols ...string) (*Friendship, error) {
	return FindFriendship(boil.GetDB(), id, selectCols...)
}

// FindFriendshipGP retrieves a single record by ID, and panics on error.
func FindFriendshipGP(id int, selectCols ...string) *Friendship {
	retobj, err := FindFriendship(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindFriendship retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFriendship(exec boil.Executor, id int, selectCols ...string) (*Friendship, error) {
	friendshipObj := &Friendship{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"friendships\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(friendshipObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from friendships")
	}

	return friendshipObj, nil
}

// FindFriendshipP retrieves a single record by ID with an executor, and panics on error.
func FindFriendshipP(exec boil.Executor, id int, selectCols ...string) *Friendship {
	retobj, err := FindFriendship(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Friendship) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Friendship) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Friendship) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Friendship) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no friendships provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(friendshipColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	friendshipInsertCacheMut.RLock()
	cache, cached := friendshipInsertCache[key]
	friendshipInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			friendshipColumns,
			friendshipColumnsWithDefault,
			friendshipColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(friendshipType, friendshipMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(friendshipType, friendshipMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"friendships\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"friendships\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into friendships")
	}

	if !cached {
		friendshipInsertCacheMut.Lock()
		friendshipInsertCache[key] = cache
		friendshipInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Friendship record. See Update for
// whitelist behavior description.
func (o *Friendship) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Friendship record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Friendship) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Friendship, and panics on error.
// See Update for whitelist behavior description.
func (o *Friendship) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Friendship.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Friendship) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	friendshipUpdateCacheMut.RLock()
	cache, cached := friendshipUpdateCache[key]
	friendshipUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			friendshipColumns,
			friendshipPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update friendships, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"friendships\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, friendshipPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(friendshipType, friendshipMapping, append(wl, friendshipPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update friendships row")
	}

	if !cached {
		friendshipUpdateCacheMut.Lock()
		friendshipUpdateCache[key] = cache
		friendshipUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q friendshipQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q friendshipQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for friendships")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o FriendshipSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o FriendshipSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o FriendshipSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FriendshipSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), friendshipPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"friendships\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, friendshipPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in friendship slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Friendship) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Friendship) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Friendship) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Friendship) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no friendships provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(friendshipColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	friendshipUpsertCacheMut.RLock()
	cache, cached := friendshipUpsertCache[key]
	friendshipUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			friendshipColumns,
			friendshipColumnsWithDefault,
			friendshipColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			friendshipColumns,
			friendshipPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert friendships, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(friendshipPrimaryKeyColumns))
			copy(conflict, friendshipPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"friendships\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(friendshipType, friendshipMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(friendshipType, friendshipMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert friendships")
	}

	if !cached {
		friendshipUpsertCacheMut.Lock()
		friendshipUpsertCache[key] = cache
		friendshipUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Friendship record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Friendship) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Friendship record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Friendship) DeleteG() error {
	if o == nil {
		return errors.New("models: no Friendship provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Friendship record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Friendship) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Friendship record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Friendship) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Friendship provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), friendshipPrimaryKeyMapping)
	sql := "DELETE FROM \"friendships\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from friendships")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q friendshipQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q friendshipQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no friendshipQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from friendships")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o FriendshipSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o FriendshipSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Friendship slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o FriendshipSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FriendshipSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Friendship slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(friendshipBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), friendshipPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"friendships\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, friendshipPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from friendship slice")
	}

	if len(friendshipAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Friendship) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Friendship) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Friendship) ReloadG() error {
	if o == nil {
		return errors.New("models: no Friendship provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Friendship) Reload(exec boil.Executor) error {
	ret, err := FindFriendship(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *FriendshipSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *FriendshipSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FriendshipSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty FriendshipSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FriendshipSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	friendships := FriendshipSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), friendshipPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"friendships\".* FROM \"friendships\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, friendshipPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&friendships)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FriendshipSlice")
	}

	*o = friendships

	return nil
}

// FriendshipExists checks if the Friendship row exists.
func FriendshipExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"friendships\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if friendships exists")
	}

	return exists, nil
}

// FriendshipExistsG checks if the Friendship row exists.
func FriendshipExistsG(id int) (bool, error) {
	return FriendshipExists(boil.GetDB(), id)
}

// FriendshipExistsGP checks if the Friendship row exists. Panics on error.
func FriendshipExistsGP(id int) bool {
	e, err := FriendshipExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// FriendshipExistsP checks if the Friendship row exists. Panics on error.
func FriendshipExistsP(exec boil.Executor, id int) bool {
	e, err := FriendshipExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
