// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/randomize"
	"github.com/vattle/sqlboiler/strmangle"
)

func testRemoteUsers(t *testing.T) {
	t.Parallel()

	query := RemoteUsers(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testRemoteUsersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = remoteUser.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRemoteUsersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = RemoteUsers(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRemoteUsersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := RemoteUserSlice{remoteUser}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testRemoteUsersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := RemoteUserExists(tx, remoteUser.RemoteID)
	if err != nil {
		t.Errorf("Unable to check if RemoteUser exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RemoteUserExistsG to return true, but got false.")
	}
}
func testRemoteUsersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	remoteUserFound, err := FindRemoteUser(tx, remoteUser.RemoteID)
	if err != nil {
		t.Error(err)
	}

	if remoteUserFound == nil {
		t.Error("want a record, got nil")
	}
}
func testRemoteUsersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = RemoteUsers(tx).Bind(remoteUser); err != nil {
		t.Error(err)
	}
}

func testRemoteUsersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := RemoteUsers(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRemoteUsersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUserOne := &RemoteUser{}
	remoteUserTwo := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUserOne, remoteUserDBTypes, false, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}
	if err = randomize.Struct(seed, remoteUserTwo, remoteUserDBTypes, false, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUserOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = remoteUserTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := RemoteUsers(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRemoteUsersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	remoteUserOne := &RemoteUser{}
	remoteUserTwo := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUserOne, remoteUserDBTypes, false, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}
	if err = randomize.Struct(seed, remoteUserTwo, remoteUserDBTypes, false, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUserOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = remoteUserTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}
func remoteUserBeforeInsertHook(e boil.Executor, o *RemoteUser) error {
	*o = RemoteUser{}
	return nil
}

func remoteUserAfterInsertHook(e boil.Executor, o *RemoteUser) error {
	*o = RemoteUser{}
	return nil
}

func remoteUserAfterSelectHook(e boil.Executor, o *RemoteUser) error {
	*o = RemoteUser{}
	return nil
}

func remoteUserBeforeUpdateHook(e boil.Executor, o *RemoteUser) error {
	*o = RemoteUser{}
	return nil
}

func remoteUserAfterUpdateHook(e boil.Executor, o *RemoteUser) error {
	*o = RemoteUser{}
	return nil
}

func remoteUserBeforeDeleteHook(e boil.Executor, o *RemoteUser) error {
	*o = RemoteUser{}
	return nil
}

func remoteUserAfterDeleteHook(e boil.Executor, o *RemoteUser) error {
	*o = RemoteUser{}
	return nil
}

func remoteUserBeforeUpsertHook(e boil.Executor, o *RemoteUser) error {
	*o = RemoteUser{}
	return nil
}

func remoteUserAfterUpsertHook(e boil.Executor, o *RemoteUser) error {
	*o = RemoteUser{}
	return nil
}

func testRemoteUsersHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &RemoteUser{}
	o := &RemoteUser{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, remoteUserDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RemoteUser object: %s", err)
	}

	AddRemoteUserHook(boil.BeforeInsertHook, remoteUserBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	remoteUserBeforeInsertHooks = []RemoteUserHook{}

	AddRemoteUserHook(boil.AfterInsertHook, remoteUserAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	remoteUserAfterInsertHooks = []RemoteUserHook{}

	AddRemoteUserHook(boil.AfterSelectHook, remoteUserAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	remoteUserAfterSelectHooks = []RemoteUserHook{}

	AddRemoteUserHook(boil.BeforeUpdateHook, remoteUserBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	remoteUserBeforeUpdateHooks = []RemoteUserHook{}

	AddRemoteUserHook(boil.AfterUpdateHook, remoteUserAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	remoteUserAfterUpdateHooks = []RemoteUserHook{}

	AddRemoteUserHook(boil.BeforeDeleteHook, remoteUserBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	remoteUserBeforeDeleteHooks = []RemoteUserHook{}

	AddRemoteUserHook(boil.AfterDeleteHook, remoteUserAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	remoteUserAfterDeleteHooks = []RemoteUserHook{}

	AddRemoteUserHook(boil.BeforeUpsertHook, remoteUserBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	remoteUserBeforeUpsertHooks = []RemoteUserHook{}

	AddRemoteUserHook(boil.AfterUpsertHook, remoteUserAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	remoteUserAfterUpsertHooks = []RemoteUserHook{}
}
func testRemoteUsersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRemoteUsersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx, remoteUserColumnsWithoutDefault...); err != nil {
		t.Error(err)
	}

	count, err := RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRemoteUserToOneUserUsingUser(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local RemoteUser
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	local.UserID.Valid = true

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.UserID.Int = foreign.ID
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.User(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RemoteUserSlice{&local}
	if err = local.L.LoadUser(tx, false, (*[]*RemoteUser)(&slice)); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRemoteUserToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a RemoteUser
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, remoteUserDBTypes, false, strmangle.SetComplement(remoteUserPrimaryKeyColumns, remoteUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RemoteUsers[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID.Int != x.ID {
			t.Error("foreign key was wrong value", a.UserID.Int)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID.Int))
		reflect.Indirect(reflect.ValueOf(&a.UserID.Int)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID.Int != x.ID {
			t.Error("foreign key was wrong value", a.UserID.Int, x.ID)
		}
	}
}

func testRemoteUserToOneRemoveOpUserUsingUser(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a RemoteUser
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, remoteUserDBTypes, false, strmangle.SetComplement(remoteUserPrimaryKeyColumns, remoteUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUser(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUser(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.User(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.User != nil {
		t.Error("R struct entry should be nil")
	}

	if a.UserID.Valid {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.RemoteUsers) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testRemoteUsersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = remoteUser.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testRemoteUsersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := RemoteUserSlice{remoteUser}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testRemoteUsersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := RemoteUsers(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	remoteUserDBTypes = map[string]string{`RemoteID`: `character varying`, `UserID`: `integer`}
	_                 = bytes.MinRead
)

func testRemoteUsersUpdate(t *testing.T) {
	t.Parallel()

	if len(remoteUserColumns) == len(remoteUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	if err = remoteUser.Update(tx); err != nil {
		t.Error(err)
	}
}

func testRemoteUsersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(remoteUserColumns) == len(remoteUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	remoteUser := &RemoteUser{}
	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, remoteUser, remoteUserDBTypes, true, remoteUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(remoteUserColumns, remoteUserPrimaryKeyColumns) {
		fields = remoteUserColumns
	} else {
		fields = strmangle.SetComplement(
			remoteUserColumns,
			remoteUserPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(remoteUser))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := RemoteUserSlice{remoteUser}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testRemoteUsersUpsert(t *testing.T) {
	t.Parallel()

	if len(remoteUserColumns) == len(remoteUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	remoteUser := RemoteUser{}
	if err = randomize.Struct(seed, &remoteUser, remoteUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = remoteUser.Upsert(tx, false, nil, nil); err != nil {
		t.Errorf("Unable to upsert RemoteUser: %s", err)
	}

	count, err := RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &remoteUser, remoteUserDBTypes, false, remoteUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RemoteUser struct: %s", err)
	}

	if err = remoteUser.Upsert(tx, true, nil, nil); err != nil {
		t.Errorf("Unable to upsert RemoteUser: %s", err)
	}

	count, err = RemoteUsers(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
